return {
  { "rafamadriz/friendly-snippets", enabled = true },
  { "L3MON4D3/LuaSnip", enabled = true },
  { "folke/flash.nvim", enabled = false },
  { "folke/noice.nvim", enabled = true },
  { "gbprod/yanky.nvim", enabled = false },
  { "kkharji/sqlite.lua", enabled = false },
  { "mfussenegger/nvim-dap", enabled = false },
  { "rcarriga/nvim-dap-ui", enabled = false },
  { "stevearc/aerial.nvim", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  { "echasnovski/mini.files", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "echasnovski/mini.bufremove", enabled = false },
  { "joosepAlviste/nvim-ts-context-commentstring", enabled = false },
  { "github/copilot.vim", enabled = false },
  { "mfussenegger/nvim-lint", enable = false },
  { "nvim-pack/nvim-spectre", enable = false },
  { "nvim-telescope/telescope-fzf-native.nvim", enable = false },
}
